---
extends: default

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  line-length:
    max: 140
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
  octal-values:
    forbid-implicit-octal: true # yamllint defaults to false
    forbid-explicit-octal: true # yamllint defaults to false
