---
# Installing parts of the role.

- name: Install | Fetch the latest and greatest
  when: matterhorn_state == "latest"
  block:
    - name: Install | Fetch the latest release information from GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/ansible/ansible/releases/latest
        return_content: true
    register: __json_reponse

  - get_url:
      url: "{{ __json_reponse.json.tarball_url }}"
      dest: ./ansible-latest.tar.gz


- name: Install | Update apt-cache
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family | lower == 'debian'

- name: Install | Install requirements
  become: true
  ansible.builtin.package:
    name: bzip2,unzip,tar
    state: present

# Download the source file
- name: Install | Download the release
  environment:
    TMPDIR: "{{ matterhorn_userhome }}/tmp"
  ansible.builtin.get_url:
    url: "{{ matterhorn_release_url }}"
    dest: "{{ matterhorn_userhome }}/matterhorn.tar.bz2"
    owner: "{{ matterhorn_username }}"
    group: "{{ matterhorn_groupname }}"

- name: Install | Decompress source file
  ansible.builtin.unarchive:
    src: "{{ matterhorn_userhome }}/matterhorn.tar.bz2"
    dest: "{{ matterhorn_userhome }}/"
    extra_opts: ['--strip-components=1', '--show-stored-names', '--wildcards']
    include:
      - "*/matterhorn"
    remote_src: true

- name: Install | Move binary file to target destination
  become: true
  ansible.builtin.copy:
    src: "{{ matterhorn_userhome }}/matterhorn"
    dest: "{{ matterhorn_dest_dir }}/"
    remote_src: true
    owner: root
    group: root
    mode: '0755'
