---
- name: No_update | Converge
  hosts: all
  tasks:

    - name: "Converge | Include variables"
      ansible.builtin.include_vars: "variables.yml"

    - name: "Converge | Include role spreadcat.matterhorn"
      ansible.builtin.include_role:
        name: "spreadcat.matterhorn"
